#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

// Import path mappings
const importMappings = {
  // Base UI components - all variations
  '../../../../../components/ui/Button': '../../../../../components/ui/base/Button',
  '../../../../components/ui/Button': '../../../../components/ui/base/Button',
  '../../../components/ui/Button': '../../../components/ui/base/Button',
  '../../components/ui/Button': '../../components/ui/base/Button',
  '../components/ui/Button': '../components/ui/base/Button',
  './Button': './base/Button',
  '../../../../../components/ui/Input': '../../../../../components/ui/base/Input',
  '../../../../components/ui/Input': '../../../../components/ui/base/Input',
  '../../../components/ui/Input': '../../../components/ui/base/Input',
  '../../components/ui/Input': '../../components/ui/base/Input',
  '../components/ui/Input': '../components/ui/base/Input',
  './Input': './base/Input',
  '../../../../../components/ui/Card': '../../../../../components/ui/base/Card',
  '../../../../components/ui/Card': '../../../../components/ui/base/Card',
  '../../../components/ui/Card': '../../../components/ui/base/Card',
  '../../components/ui/Card': '../../components/ui/base/Card',
  '../components/ui/Card': '../components/ui/base/Card',
  './Card': './base/Card',
  '../../../../../components/ui/Badge': '../../../../../components/ui/base/Badge',
  '../../../../components/ui/Badge': '../../../../components/ui/base/Badge',
  '../../../components/ui/Badge': '../../../components/ui/base/Badge',
  '../../components/ui/Badge': '../../components/ui/base/Badge',
  '../components/ui/Badge': '../components/ui/base/Badge',
  './Badge': './base/Badge',
  '../../../../../components/ui/Label': '../../../../../components/ui/base/Label',
  '../../../../components/ui/Label': '../../../../components/ui/base/Label',
  '../../../components/ui/Label': '../../../components/ui/base/Label',
  '../../components/ui/Label': '../../components/ui/base/Label',
  '../components/ui/Label': '../components/ui/base/Label',
  './Label': './base/Label',
  '../../../../../components/ui/Alert': '../../../../../components/ui/base/Alert',
  '../../../../components/ui/Alert': '../../../../components/ui/base/Alert',
  '../../../components/ui/Alert': '../../../components/ui/base/Alert',
  '../../components/ui/Alert': '../../components/ui/base/Alert',
  '../components/ui/Alert': '../components/ui/base/Alert',
  './Alert': './base/Alert',
  '../../../../../components/ui/Avatar': '../../../../../components/ui/base/Avatar',
  '../../../../components/ui/Avatar': '../../../../components/ui/base/Avatar',
  '../../../components/ui/Avatar': '../../../components/ui/base/Avatar',
  '../../components/ui/Avatar': '../../components/ui/base/Avatar',
  '../components/ui/Avatar': '../components/ui/base/Avatar',
  './Avatar': './base/Avatar',
  '../../../../../components/ui/Switch': '../../../../../components/ui/base/Switch',
  '../../../../components/ui/Switch': '../../../../components/ui/base/Switch',
  '../../../components/ui/Switch': '../../../components/ui/base/Switch',
  '../../components/ui/Switch': '../../components/ui/base/Switch',
  '../components/ui/Switch': '../components/ui/base/Switch',
  './Switch': './base/Switch',
  '../../../../../components/ui/Textarea': '../../../../../components/ui/base/Textarea',
  '../../../../components/ui/Textarea': '../../../../components/ui/base/Textarea',
  '../../../components/ui/Textarea': '../../../components/ui/base/Textarea',
  '../../components/ui/Textarea': '../../components/ui/base/Textarea',
  '../components/ui/Textarea': '../components/ui/base/Textarea',
  './Textarea': './base/Textarea',
  '../../../../../components/ui/Checkbox': '../../../../../components/ui/base/Checkbox',
  '../../../../components/ui/Checkbox': '../../../../components/ui/base/Checkbox',
  '../../../components/ui/Checkbox': '../../../components/ui/base/Checkbox',
  '../../components/ui/Checkbox': '../../components/ui/base/Checkbox',
  '../components/ui/Checkbox': '../components/ui/base/Checkbox',
  './Checkbox': './base/Checkbox',
  
  // Composite UI components
  '../../../../components/ui/Dialog': '../../../../components/ui/composite/Dialog',
  '../../../components/ui/Dialog': '../../../components/ui/composite/Dialog',
  '../../components/ui/Dialog': '../../components/ui/composite/Dialog',
  '../components/ui/Dialog': '../components/ui/composite/Dialog',
  './Dialog': './composite/Dialog',
  '../../../../components/ui/DropdownMenu': '../../../../components/ui/composite/DropdownMenu',
  '../../../components/ui/DropdownMenu': '../../../components/ui/composite/DropdownMenu',
  '../../components/ui/DropdownMenu': '../../components/ui/composite/DropdownMenu',
  '../components/ui/DropdownMenu': '../components/ui/composite/DropdownMenu',
  './DropdownMenu': './composite/DropdownMenu',
  '../../../../components/ui/Tabs': '../../../../components/ui/composite/Tabs',
  '../../../components/ui/Tabs': '../../../components/ui/composite/Tabs',
  '../../components/ui/Tabs': '../../components/ui/composite/Tabs',
  '../components/ui/Tabs': '../components/ui/composite/Tabs',
  './Tabs': './composite/Tabs',
  '../../../../components/ui/accordion': '../../../../components/ui/composite/accordion',
  '../../../components/ui/accordion': '../../../components/ui/composite/accordion',
  '../../components/ui/accordion': '../../components/ui/composite/accordion',
  '../components/ui/accordion': '../components/ui/composite/accordion',
  './accordion': './composite/accordion',
  
  // Feedback components
  '../../../../components/ui/Toast': '../../../../components/ui/feedback/Toast',
  '../../../components/ui/Toast': '../../../components/ui/feedback/Toast',
  '../../components/ui/Toast': '../../components/ui/feedback/Toast',
  '../components/ui/Toast': '../components/ui/feedback/Toast',
  './Toast': './feedback/Toast',
  '../../../../components/ui/use-toast': '../../../../components/ui/feedback/use-toast',
  '../../../components/ui/use-toast': '../../../components/ui/feedback/use-toast',
  '../../components/ui/use-toast': '../../components/ui/feedback/use-toast',
  '../components/ui/use-toast': '../components/ui/feedback/use-toast',
  './use-toast': './feedback/use-toast',
  '../../../../components/ui/Toaster': '../../../../components/ui/feedback/Toaster',
  '../../../components/ui/Toaster': '../../../components/ui/feedback/Toaster',
  '../../components/ui/Toaster': '../../components/ui/feedback/Toaster',
  '../components/ui/Toaster': '../components/ui/feedback/Toaster',
  './Toaster': './feedback/Toaster',
  '../../../../components/ui/ErrorBoundary': '../../../../components/ui/feedback/ErrorBoundary',
  '../../../components/ui/ErrorBoundary': '../../../components/ui/feedback/ErrorBoundary',
  '../../components/ui/ErrorBoundary': '../../components/ui/feedback/ErrorBoundary',
  '../components/ui/ErrorBoundary': '../components/ui/feedback/ErrorBoundary',
  './ErrorBoundary': './feedback/ErrorBoundary',
  '../../../../components/ui/ApiErrorBoundary': '../../../../components/ui/feedback/ApiErrorBoundary',
  '../../../components/ui/ApiErrorBoundary': '../../../components/ui/feedback/ApiErrorBoundary',
  '../../components/ui/ApiErrorBoundary': '../../components/ui/feedback/ApiErrorBoundary',
  '../components/ui/ApiErrorBoundary': '../components/ui/feedback/ApiErrorBoundary',
  './ApiErrorBoundary': './feedback/ApiErrorBoundary',
  '../../../../components/ui/LoadingSpinner': '../../../../components/ui/feedback/LoadingSpinner',
  '../../../components/ui/LoadingSpinner': '../../../components/ui/feedback/LoadingSpinner',
  '../../components/ui/LoadingSpinner': '../../components/ui/feedback/LoadingSpinner',
  '../components/ui/LoadingSpinner': '../components/ui/feedback/LoadingSpinner',
  './LoadingSpinner': './feedback/LoadingSpinner',
  '../../../../components/ui/LoadingButton': '../../../../components/ui/feedback/LoadingButton',
  '../../../components/ui/LoadingButton': '../../../components/ui/feedback/LoadingButton',
  '../../components/ui/LoadingButton': '../../components/ui/feedback/LoadingButton',
  '../components/ui/LoadingButton': '../components/ui/feedback/LoadingButton',
  './LoadingButton': './feedback/LoadingButton',
  '../../../../components/ui/LoadingCard': '../../../../components/ui/feedback/LoadingCard',
  '../../../components/ui/LoadingCard': '../../../components/ui/feedback/LoadingCard',
  '../../components/ui/LoadingCard': '../../components/ui/feedback/LoadingCard',
  '../components/ui/LoadingCard': '../components/ui/feedback/LoadingCard',
  './LoadingCard': './feedback/LoadingCard',
  '../../../../components/ui/LoadingSkeleton': '../../../../components/ui/feedback/LoadingSkeleton',
  '../../../components/ui/LoadingSkeleton': '../../../components/ui/feedback/LoadingSkeleton',
  '../../components/ui/LoadingSkeleton': '../../components/ui/feedback/LoadingSkeleton',
  '../components/ui/LoadingSkeleton': '../components/ui/feedback/LoadingSkeleton',
  './LoadingSkeleton': './feedback/LoadingSkeleton',
  '../../../../components/ui/GlobalLoadingOverlay': '../../../../components/ui/feedback/GlobalLoadingOverlay',
  '../../../components/ui/GlobalLoadingOverlay': '../../../components/ui/feedback/GlobalLoadingOverlay',
  '../../components/ui/GlobalLoadingOverlay': '../../components/ui/feedback/GlobalLoadingOverlay',
  '../components/ui/GlobalLoadingOverlay': '../components/ui/feedback/GlobalLoadingOverlay',
  './GlobalLoadingOverlay': './feedback/GlobalLoadingOverlay',
  '../../../../components/ui/ProgressBar': '../../../../components/ui/feedback/ProgressBar',
  '../../../components/ui/ProgressBar': '../../../components/ui/feedback/ProgressBar',
  '../../components/ui/ProgressBar': '../../components/ui/feedback/ProgressBar',
  '../components/ui/ProgressBar': '../components/ui/feedback/ProgressBar',
  './ProgressBar': './feedback/ProgressBar',
  
  // Layout components
  '../../../../components/ui/Sidebar': '../../../../components/layout/Sidebar',
  '../../../components/ui/Sidebar': '../../../components/layout/Sidebar',
  '../../components/ui/Sidebar': '../../components/layout/Sidebar',
  '../components/ui/Sidebar': '../components/layout/Sidebar',
  './Sidebar': '../layout/Sidebar',
  '../../../../components/ui/DashboardSidebar': '../../../../components/layout/DashboardSidebar',
  '../../../components/ui/DashboardSidebar': '../../../components/layout/DashboardSidebar',
  '../../components/ui/DashboardSidebar': '../../components/layout/DashboardSidebar',
  '../components/ui/DashboardSidebar': '../components/layout/DashboardSidebar',
  './DashboardSidebar': '../layout/DashboardSidebar',
  '../../../../components/ui/DashboardHeader': '../../../../components/layout/DashboardHeader',
  '../../../components/ui/DashboardHeader': '../../../components/layout/DashboardHeader',
  '../../components/ui/DashboardHeader': '../../components/layout/DashboardHeader',
  '../components/ui/DashboardHeader': '../components/layout/DashboardHeader',
  './DashboardHeader': '../layout/DashboardHeader',
  '../../../../components/ui/LandingHeader': '../../../../components/layout/LandingHeader',
  '../../../components/ui/LandingHeader': '../../../components/layout/LandingHeader',
  '../../components/ui/LandingHeader': '../../components/layout/LandingHeader',
  '../components/ui/LandingHeader': '../components/layout/LandingHeader',
  './LandingHeader': '../layout/LandingHeader',
  
  // Feature components
  '../../../../components/ui/UsageTracker': '../../../../components/features/dashboard/UsageTracker',
  '../../../components/ui/UsageTracker': '../../../components/features/dashboard/UsageTracker',
  '../../components/ui/UsageTracker': '../../components/features/dashboard/UsageTracker',
  '../components/ui/UsageTracker': '../components/features/dashboard/UsageTracker',
  './UsageTracker': '../features/dashboard/UsageTracker',
  '../../../../components/ui/UsageWarning': '../../../../components/features/dashboard/UsageWarning',
  '../../../components/ui/UsageWarning': '../../../components/features/dashboard/UsageWarning',
  '../../components/ui/UsageWarning': '../../components/features/dashboard/UsageWarning',
  '../components/ui/UsageWarning': '../components/features/dashboard/UsageWarning',
  './UsageWarning': '../features/dashboard/UsageWarning',
  '../../../../components/ui/UsageBadge': '../../../../components/features/dashboard/UsageBadge',
  '../../../components/ui/UsageBadge': '../../../components/features/dashboard/UsageBadge',
  '../../components/ui/UsageBadge': '../../components/features/dashboard/UsageBadge',
  '../components/ui/UsageBadge': '../components/features/dashboard/UsageBadge',
  './UsageBadge': '../features/dashboard/UsageBadge',
  '../../../../components/ui/SaveResumeDialog': '../../../../components/features/resume/SaveResumeDialog',
  '../../../components/ui/SaveResumeDialog': '../../../components/features/resume/SaveResumeDialog',
  '../../components/ui/SaveResumeDialog': '../../components/features/resume/SaveResumeDialog',
  '../components/ui/SaveResumeDialog': '../components/features/resume/SaveResumeDialog',
  './SaveResumeDialog': '../features/resume/SaveResumeDialog',
  '../../../../components/ui/ResumeUploadDialog': '../../../../components/features/resume/ResumeUploadDialog',
  '../../../components/ui/ResumeUploadDialog': '../../../components/features/resume/ResumeUploadDialog',
  '../../components/ui/ResumeUploadDialog': '../../components/features/resume/ResumeUploadDialog',
  '../components/ui/ResumeUploadDialog': '../components/features/resume/ResumeUploadDialog',
  './ResumeUploadDialog': '../features/resume/ResumeUploadDialog',
  '../../../../components/ui/ResumeUpload': '../../../../components/features/resume/ResumeUpload',
  '../../../components/ui/ResumeUpload': '../../../components/features/resume/ResumeUpload',
  '../../components/ui/ResumeUpload': '../../components/features/resume/ResumeUpload',
  '../components/ui/ResumeUpload': '../components/features/resume/ResumeUpload',
  './ResumeUpload': '../features/resume/ResumeUpload',
  '../../../../components/ui/JobDescriptionInput': '../../../../components/features/resume/JobDescriptionInput',
  '../../../components/ui/JobDescriptionInput': '../../../components/features/resume/JobDescriptionInput',
  '../../components/ui/JobDescriptionInput': '../../components/features/resume/JobDescriptionInput',
  '../components/ui/JobDescriptionInput': '../components/features/resume/JobDescriptionInput',
  './JobDescriptionInput': '../features/resume/JobDescriptionInput',
  '../../../../components/ui/FeedbackWidget': '../../../../components/features/feedback/FeedbackWidget',
  '../../../components/ui/FeedbackWidget': '../../../components/features/feedback/FeedbackWidget',
  '../../components/ui/FeedbackWidget': '../../components/features/feedback/FeedbackWidget',
  '../components/ui/FeedbackWidget': '../components/features/feedback/FeedbackWidget',
  './FeedbackWidget': '../features/feedback/FeedbackWidget',
  '../../../../components/ui/LimitExceededDialog': '../../../../components/features/dashboard/LimitExceededDialog',
  '../../../components/ui/LimitExceededDialog': '../../../components/features/dashboard/LimitExceededDialog',
  '../../components/ui/LimitExceededDialog': '../../components/features/dashboard/LimitExceededDialog',
  '../components/ui/LimitExceededDialog': '../components/features/dashboard/LimitExceededDialog',
  './LimitExceededDialog': '../features/dashboard/LimitExceededDialog',
  '../../../../components/ui/TicketId': '../../../../components/features/feedback/TicketId',
  '../../../components/ui/TicketId': '../../../components/features/feedback/TicketId',
  '../../components/ui/TicketId': '../../components/features/feedback/TicketId',
  '../components/ui/TicketId': '../components/features/feedback/TicketId',
  './TicketId': '../features/feedback/TicketId',
  
  // Providers
  '../../../../components/ClientProviders': '../../../../components/providers/ClientProviders',
  '../../../components/ClientProviders': '../../../components/providers/ClientProviders',
  '../../components/ClientProviders': '../../components/providers/ClientProviders',
  '../components/ClientProviders': '../components/providers/ClientProviders',
  './ClientProviders': './providers/ClientProviders',
  '../../../../components/ui/ClientOnly': '../../../../components/providers/ClientOnly',
  '../../../components/ui/ClientOnly': '../../../components/providers/ClientOnly',
  '../../components/ui/ClientOnly': '../../components/providers/ClientOnly',
  '../components/ui/ClientOnly': '../components/providers/ClientOnly',
  './ClientOnly': '../providers/ClientOnly',
  
  // Hooks
  '../../../../hooks/useSavedResumes': '../../../../hooks/api/useSavedResumes',
  '../../../hooks/useSavedResumes': '../../../hooks/api/useSavedResumes',
  '../../hooks/useSavedResumes': '../../hooks/api/useSavedResumes',
  '../hooks/useSavedResumes': '../hooks/api/useSavedResumes',
  './useSavedResumes': './api/useSavedResumes',
  '../../../../hooks/useSavedResumesCached': '../../../../hooks/api/useSavedResumesCached',
  '../../../hooks/useSavedResumesCached': '../../../hooks/api/useSavedResumesCached',
  '../../hooks/useSavedResumesCached': '../../hooks/api/useSavedResumesCached',
  '../hooks/useSavedResumesCached': '../hooks/api/useSavedResumesCached',
  './useSavedResumesCached': './api/useSavedResumesCached',
  '../../../../hooks/useApi': '../../../../hooks/api/useApi',
  '../../../hooks/useApi': '../../../hooks/api/useApi',
  '../../hooks/useApi': '../../hooks/api/useApi',
  '../hooks/useApi': '../hooks/api/useApi',
  './useApi': './api/useApi',
  '../../../../hooks/useAsyncOperation': '../../../../hooks/ui/useAsyncOperation',
  '../../../hooks/useAsyncOperation': '../../../hooks/ui/useAsyncOperation',
  '../../hooks/useAsyncOperation': '../../hooks/ui/useAsyncOperation',
  '../hooks/useAsyncOperation': '../hooks/ui/useAsyncOperation',
  './useAsyncOperation': './ui/useAsyncOperation',
  
  // Lib files
  '../../../../../lib/utils': '../../../../../lib/core/utils',
  '../../../../lib/utils': '../../../../lib/core/utils',
  '../../../lib/utils': '../../../lib/core/utils',
  '../../lib/utils': '../../lib/core/utils',
  '../lib/utils': '../lib/core/utils',
  './utils': './core/utils',
  '../../../../../lib/cache': '../../../../../lib/core/cache',
  '../../../../lib/cache': '../../../../lib/core/cache',
  '../../../lib/cache': '../../../lib/core/cache',
  '../../lib/cache': '../../lib/core/cache',
  '../lib/cache': '../lib/core/cache',
  './cache': './core/cache',
  '../../../../../lib/logger': '../../../../../lib/core/logger',
  '../../../../lib/logger': '../../../../lib/core/logger',
  '../../../lib/logger': '../../../lib/core/logger',
  '../../lib/logger': '../../lib/core/logger',
  '../lib/logger': '../lib/core/logger',
  './logger': './core/logger',
  '../../../../../lib/supabaseClient': '../../../../../lib/auth/supabaseClient',
  '../../../../lib/supabaseClient': '../../../../lib/auth/supabaseClient',
  '../../../lib/supabaseClient': '../../../lib/auth/supabaseClient',
  '../../lib/supabaseClient': '../../lib/auth/supabaseClient',
  '../lib/supabaseClient': '../lib/auth/supabaseClient',
  './supabaseClient': './auth/supabaseClient',
  '../../../../../lib/userOperations': '../../../../../lib/auth/userOperations',
  '../../../../lib/userOperations': '../../../../lib/auth/userOperations',
  '../../../lib/userOperations': '../../../lib/auth/userOperations',
  '../../lib/userOperations': '../../lib/auth/userOperations',
  '../lib/userOperations': '../lib/auth/userOperations',
  './userOperations': './auth/userOperations',
  '../../../../../lib/userRateLimit': '../../../../../lib/auth/userRateLimit',
  '../../../../lib/userRateLimit': '../../../../lib/auth/userRateLimit',
  '../../../lib/userRateLimit': '../../../lib/auth/userRateLimit',
  '../../lib/userRateLimit': '../../lib/auth/userRateLimit',
  '../lib/userRateLimit': '../lib/auth/userRateLimit',
  './userRateLimit': './auth/userRateLimit',
  '../../../../../lib/api-client': '../../../../../lib/api/api-client',
  '../../../../lib/api-client': '../../../../lib/api/api-client',
  '../../../lib/api-client': '../../../lib/api/api-client',
  '../../lib/api-client': '../../lib/api/api-client',
  '../lib/api-client': '../lib/api/api-client',
  './api-client': './api/api-client',
  '../../../../../lib/rateLimit': '../../../../../lib/api/rateLimit',
  '../../../../lib/rateLimit': '../../../../lib/api/rateLimit',
  '../../../lib/rateLimit': '../../../lib/api/rateLimit',
  '../../lib/rateLimit': '../../lib/api/rateLimit',
  '../lib/rateLimit': '../lib/api/rateLimit',
  './rateLimit': './api/rateLimit',
  '../../../../../lib/errorReporting-simple': '../../../../../lib/api/errorReporting-simple',
  '../../../../lib/errorReporting-simple': '../../../../lib/api/errorReporting-simple',
  '../../../lib/errorReporting-simple': '../../../lib/api/errorReporting-simple',
  '../../lib/errorReporting-simple': '../../lib/api/errorReporting-simple',
  '../lib/errorReporting-simple': '../lib/api/errorReporting-simple',
  './errorReporting-simple': './api/errorReporting-simple',
  '../../../../../lib/resumeService': '../../../../../lib/services/resumeService',
  '../../../../lib/resumeService': '../../../../lib/services/resumeService',
  '../../../lib/resumeService': '../../../lib/services/resumeService',
  '../../lib/resumeService': '../../lib/services/resumeService',
  '../lib/resumeService': '../lib/services/resumeService',
  './resumeService': './services/resumeService',
  '../../../../../lib/service-worker': '../../../../../lib/services/service-worker',
  '../../../../lib/service-worker': '../../../../lib/services/service-worker',
  '../../../lib/service-worker': '../../../lib/services/service-worker',
  '../../lib/service-worker': '../../lib/services/service-worker',
  '../lib/service-worker': '../lib/services/service-worker',
  './service-worker': './services/service-worker',
  '../../../../../lib/resume/scoreResume': '../../../../../lib/services/resume/scoreResume',
  '../../../../lib/resume/scoreResume': '../../../../lib/services/resume/scoreResume',
  '../../../lib/resume/scoreResume': '../../../lib/services/resume/scoreResume',
  '../../lib/resume/scoreResume': '../../lib/services/resume/scoreResume',
  '../lib/resume/scoreResume': '../lib/services/resume/scoreResume',
  './scoreResume': '../scoreResume',
  
  // Resume lib paths
  '../lib/resume/': '../lib/services/resume/',
  '../../lib/resume/': '../../lib/services/resume/',
  '../../../lib/resume/': '../../../lib/services/resume/',
  '../../../../lib/resume/': '../../../../lib/services/resume/',
  '../../../../../lib/resume/': '../../../../../lib/services/resume/',
  
  // Types
  '../../../../../types/savedResume': '../../../../../types/api/savedResume',
  '../../../../types/savedResume': '../../../../types/api/savedResume',
  '../../../types/savedResume': '../../../types/api/savedResume',
  '../../types/savedResume': '../../types/api/savedResume',
  '../types/savedResume': '../types/api/savedResume',
  './savedResume': './api/savedResume'
};

function updateImportsInFile(filePath) {
  try {
    let content = fs.readFileSync(filePath, 'utf8');
    let updated = false;
    
    for (const [oldPath, newPath] of Object.entries(importMappings)) {
      const importRegex = new RegExp(`(['"])${oldPath.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}(['"])`, 'g');
      if (importRegex.test(content)) {
        content = content.replace(importRegex, `$1${newPath}$2`);
        updated = true;
      }
    }
    
    if (updated) {
      fs.writeFileSync(filePath, content);
      console.log(`Updated imports in: ${filePath}`);
    }
  } catch (error) {
    console.error(`Error updating ${filePath}:`, error.message);
  }
}

function findTypescriptFiles(dir, files = []) {
  const entries = fs.readdirSync(dir);
  
  for (const entry of entries) {
    const fullPath = path.join(dir, entry);
    const stat = fs.statSync(fullPath);
    
    if (stat.isDirectory() && !['node_modules', '.next', '.git', '__tests__'].includes(entry)) {
      findTypescriptFiles(fullPath, files);
    } else if (stat.isFile() && (entry.endsWith('.ts') || entry.endsWith('.tsx'))) {
      files.push(fullPath);
    }
  }
  
  return files;
}

// Find all TypeScript files and update them
const typescriptFiles = findTypescriptFiles('.');
console.log(`Found ${typescriptFiles.length} TypeScript files`);

typescriptFiles.forEach(updateImportsInFile);

console.log('Import update completed!'); 